# Generated by Django 3.0.7 on 2020-12-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201211_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality_rating',
            name='resolution_time',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quality_rating',
            name='user',
            field=models.TextField(null=True),
        ),
    ]
